name: Release

on:
  workflow_run:
    workflows: [Validate]
    types:
      - completed

jobs:
  publish:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build:all

      - name: Create release pull request and publish to NPM
        uses: changesets/action@v1
        with: 
          version: pnpm version:ci 
          publish: pnpm publish:ci
          commit: "chore: new release"
          title: "chore: new release [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
