name: Validate

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.18.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build:all

      - name: Lint packages:
        run: pnpm lint:all

      - name: Test packages:
        run: pnpm test:all
